image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

before_build:
  - dotnet restore

build:
  project: Serilog.Sinks.Splunk.CustomFormatter.sln

after_build:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: Serilog.Sinks.Splunk.CustomFormatter\bin\Release\netstandard2.0\Serilog.Sinks.Splunk.CustomFormatter.dll
    name: Serilog.Sinks.Splunk.CustomFormatter.dll
  - path: Serilog.Sinks.Splunk.CustomFormatter\bin\Release\Serilog.Sinks.Splunk.CustomFormatter.%version%.nupkg
    name: Serilog.Sinks.Splunk.CustomFormatter.%version%.nupkg

deploy:
  provider: NuGet
  server: https://ci.appveyor.com/nuget/psantiago32-v5m035s3msh3
  api_key:
    secure: qv/rCMFTu6BRtENP7hS+++jGJps6Api481M+uymDtbA=
